export const UPDATE_APP = 'UPDATE_APP';

export const UPDATE_CHATAPP = 'UPDATE_CHATAPP';

export const UPDATE_COLLABORATIONAPP = 'UPDATE_COLLABORATIONAPP';

export const SET_INSTANCE = 'SET_INSTANCE';

export const IN_PROGRESS = 'IN_PROGRESS';

export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';

export const LOGIN = 'LOGIN';

export const LOGOUT = 'LOGOUT';

export const INIT_INSTANCE = 'INIT_INSTANCE';

export const SEARCH_ENTITIES = 'SEARCH_ENTITIES';

export const FILTER_CLEAR = 'FILTER_CLEAR';

export const FILTER_ENTITIES = 'FILTER_ENTITIES';

export const SET_CONNECTION_STATE = 'SET_CONNECTION_STATE';

export const SET_URL_STATE = 'SET_URL_STATE';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';

export const LOAD_ADAPTERS = 'LOAD_ADAPTERS';

export const UPDATE_GLOBAL_PROPS = 'UPDATE_GLOBAL_PROPS';

export const UPDATE_NAVIGATION = 'UPDATE_NAVIGATION';

export const OPEN_DRAWER = 'OPEN_DRAWER';

export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const OPEN_CHATAPP = 'OPEN_CHATAPP';

export const OPEN_COLLABORATION_RIGHT = 'OPEN_COLLABORATION_RIGHT';

export const CLOSE_COLLABORATION_RIGHT = 'CLOSE_COLLABORATION_RIGHT';

export const CLOSE_CHATAPP = 'CLOSE_CHATAPP';

export const ADD_CHATAPP_INTEGRATION = 'ADD_CHATAPP_INTEGRATION';

export const REMOVE_CHATAPP_INTEGRATION = 'REMOVE_CHATAPP_INTEGRATION';

export const UPDATE_CHATAPP_RIGHT = 'UPDATE_CHATAPP_RIGHT';

export const UPDATE_COLLABORATION_RIGHT = 'UPDATE_COLLABORATION_RIGHT';